import { Category, Provider } from "../types";

export const CATEGORIES: Category[] = [
  {
    id: "electricians",
    name: "Electricians",
    icon: "Zap",
    emoji: "⚡",
    description: "Wiring, short circuits, UPS setup, generator maintenance & solar panel installations.",
    providerCount: 148,
    avgPrice: "Rs. 800 - 3,500",
  },
  {
    id: "plumbers",
    name: "Plumbers",
    icon: "Wrench",
    emoji: "🔧",
    description: "Pipe leakage fix, sanitary fittings, water motor repair, tank cleaning & geyser repair.",
    providerCount: 126,
    avgPrice: "Rs. 1,000 - 4,000",
  },
  {
    id: "tutors",
    name: "Tutors",
    icon: "BookOpen",
    emoji: "📚",
    description: "Home & online tutors for Matric, FSc, O/A Levels, MDCAT, IELTS & Quranic studies.",
    providerCount: 210,
    avgPrice: "Rs. 8,000 - 25,000/mo",
  },
  {
    id: "photographers",
    name: "Photographers",
    icon: "Camera",
    emoji: "📷",
    description: "Wedding cinematography, event coverage, portrait shoots, product & drone photography.",
    providerCount: 84,
    avgPrice: "Rs. 15,000 - 80,000",
  },
  {
    id: "mechanics",
    name: "Mechanics",
    icon: "Car",
    emoji: "🚗",
    description: "On-site emergency car mechanics, engine tuning, brake pads, oil change & computer diagnosis.",
    providerCount: 98,
    avgPrice: "Rs. 1,200 - 6,000",
  },
  {
    id: "car_wash",
    name: "Car Wash",
    icon: "Sparkles",
    emoji: "🧼",
    description: "Doorstep detailing, steam interior cleaning, ceramic coating & foam wash at home.",
    providerCount: 72,
    avgPrice: "Rs. 1,500 - 5,000",
  },
  {
    id: "ac_repair",
    name: "AC Repair",
    icon: "Wind",
    emoji: "🛠️",
    description: "Inverter AC servicing, gas refilling, master jet wash, PCB repair & new installation.",
    providerCount: 165,
    avgPrice: "Rs. 1,500 - 4,500",
  },
  {
    id: "painters",
    name: "Painters",
    icon: "Paintbrush",
    emoji: "🎨",
    description: "Interior & exterior house painting, wall accent texture, damp proofing & whitewash.",
    providerCount: 91,
    avgPrice: "Rs. 15 - 35 / sq.ft",
  },
  {
    id: "home_cleaning",
    name: "Home Cleaning",
    icon: "Home",
    emoji: "🏠",
    description: "Deep house cleaning, sofa wash, carpet shampooing, kitchen degreasing & fumigation.",
    providerCount: 115,
    avgPrice: "Rs. 3,500 - 12,000",
  },
  {
    id: "garden_services",
    name: "Garden Services",
    icon: "Trees",
    emoji: "🌿",
    description: "Lawn mowing, tree trimming, artificial grass installation, pest control & garden design.",
    providerCount: 63,
    avgPrice: "Rs. 2,000 - 7,500",
  },
];

export const PAKISTAN_CITIES_MAP: Record<string, string[]> = {
  Islamabad: [
    "Bahria Town Phase 1-8",
    "DHA Phase 2 & 5",
    "F-6 / F-7 / F-8",
    "F-10 / F-11",
    "G-9 / G-10 / G-11",
    "G-13 / G-14",
    "E-11 / D-12",
    "PWD / Police Foundation",
    "Gulberg Greens",
    "Park View City",
  ],
  Rawalpindi: [
    "Satellite Town",
    "Saddar Cantt",
    "Peshawar Road",
    "Westridge",
    "Bahria Town Phase 8",
    "Chaklala Scheme 3",
    "Adiala Road",
    "Commercial Market",
    "Khayaban-e-Sir Syed",
  ],
  Lahore: [
    "Gulberg I, II & III",
    "DHA Phase 1-8",
    "Johar Town",
    "Model Town",
    "Bahria Town Lahore",
    "Askari 10 & 11",
    "Faisal Town",
    "Cantt Lahore",
    "WAPDA Town",
    "Allama Iqbal Town",
  ],
  Karachi: [
    "Clifton Block 1-9",
    "DHA Phase 1-8",
    "PECHS / Tariq Road",
    "Gulshan-e-Iqbal",
    "Gulistan-e-Johar",
    "North Nazimabad",
    "Bahria Town Karachi",
    "FB Area",
    "Defense View",
    "Korangi Industrial Area",
  ],
  Peshawar: [
    "Hayatabad Phase 1-7",
    "University Town",
    "Cantt Peshawar",
    "Warsak Road",
    "Ring Road",
    "Dalazak Road",
  ],
  Faisalabad: [
    "Civil Lines",
    "People's Colony 1 & 2",
    "Gulberg Faisalabad",
    "D-Ground",
    "Canal Road",
    "Samanabad",
  ],
  Multan: [
    "Cantt Multan",
    "Gulgasht Colony",
    "WAPDA Town Multan",
    "Bosana Road",
    "New Multan",
  ],
  Quetta: [
    "Cantt Quetta",
    "Shahbaz Town",
    "Jinnah Town",
    "Brewery Road",
    "Air Port Road",
  ],
  Sialkot: [
    "Model Town Sialkot",
    "Cantt Sialkot",
    "Kashmiri Mohallah",
    "Daska Road",
  ],
  Gujranwala: [
    "DC Colony",
    "Garden Town Gujranwala",
    "Wapda Town",
    "Model Town",
  ],
};

export const INITIAL_PROVIDERS: Provider[] = [
  {
    id: "p-101",
    name: "Muhammad Ali",
    profession: "Master Electrician & Solar Expert",
    categoryId: "electricians",
    city: "Islamabad",
    area: "Bahria Town Phase 8",
    phone: "+92 300 1234567",
    whatsapp: "+92 300 1234567",
    email: "m.ali.electric@gmail.com",
    experienceYears: 7,
    rating: 4.9,
    reviewCount: 142,
    isAvailable: true,
    availabilityText: "Available Now (20 mins response)",
    startingPrice: "Rs. 1,000",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300",
    cnicVerified: true,
    policeChecked: true,
    bio: "Certified electrical engineer with over 7 years of hands-on experience handling complex house wiring, breaker repairs, inverter UPS configurations, and rooftop solar installations across Islamabad & Rawalpindi.",
    servicesOffered: [
      "House Wiring & Rewiring",
      "Short Circuit Diagnosis",
      "Inverter UPS Setup",
      "Solar Panel Wiring & Inverter Repair",
      "DB Box & Breaker Replacement",
    ],
    reviewsList: [
      {
        id: "r1",
        authorName: "Kamran Khan",
        city: "Islamabad",
        rating: 5,
        date: "2 days ago",
        comment: "Muhammad Ali arrived within 25 minutes in Bahria Town Phase 8 and diagnosed a tricky short circuit. Highly polite and professional!",
      },
      {
        id: "r2",
        authorName: "Dr. Sarah Ahmed",
        city: "Islamabad",
        rating: 5,
        date: "1 week ago",
        comment: "Installed our 10kW solar hybrid inverter system. Very clean neat work!",
      },
    ],
  },
  {
    id: "p-102",
    name: "Tariq Mahmood",
    profession: "Sanitary & Master Plumber",
    categoryId: "plumbers",
    city: "Lahore",
    area: "DHA Phase 5",
    phone: "+92 321 9876543",
    whatsapp: "+92 321 9876543",
    email: "tariq.plumbing@gmail.com",
    experienceYears: 10,
    rating: 4.8,
    reviewCount: 98,
    isAvailable: true,
    availabilityText: "Available Now (Emergency Service)",
    startingPrice: "Rs. 1,200",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300",
    cnicVerified: true,
    policeChecked: true,
    bio: "10+ years fixing plumbing emergencies in DHA & Gulberg Lahore. Specialist in PPRC pipe fitting, automatic pressure pump setup, gas geyser repair, and underground tank leakages.",
    servicesOffered: [
      "PPRC & PVC Pipe Installation",
      "Water Tank Cleaning & Leakage Fix",
      "Instant & Gas Geyser Repair",
      "Sanitary Mixer Tap Fitting",
      "Automatic Pressure Pump Fix",
    ],
    reviewsList: [
      {
        id: "r3",
        authorName: "Usman Ghani",
        city: "Lahore",
        rating: 5,
        date: "Yesterday",
        comment: "Fixed a major pipe leak behind the bathroom tiles without breaking extra walls. Saved us thousands!",
      },
    ],
  },
  {
    id: "p-103",
    name: "Ayesha Malik",
    profession: "O/A Level & MDCAT Physics Tutor",
    categoryId: "tutors",
    city: "Islamabad",
    area: "F-7 / F-8",
    phone: "+92 333 4567890",
    whatsapp: "+92 333 4567890",
    email: "ayesha.tutor.pk@gmail.com",
    experienceYears: 6,
    rating: 5.0,
    reviewCount: 65,
    isAvailable: true,
    availabilityText: "Accepting 2 New Students",
    startingPrice: "Rs. 15,000 / mo",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300",
    cnicVerified: true,
    policeChecked: true,
    bio: "MSc Physics graduate from NUST. Specializing in Cambridge O/A Level Physics, Mathematics, and MDCAT entrance prep. Proven track record of student A* grades.",
    servicesOffered: [
      "O Level & IGCSE Physics",
      "A Level Mechanics & Physics",
      "MDCAT & ECAT Preparation",
      "Matric & FSc Board Classes",
    ],
    reviewsList: [
      {
        id: "r4",
        authorName: "Mrs. Bilal",
        city: "Islamabad",
        rating: 5,
        date: "3 weeks ago",
        comment: "Ma'am Ayesha tutored my daughter for A-Levels Physics and she achieved an A*! Exceptionally dedicated teacher.",
      },
    ],
  },
  {
    id: "p-104",
    name: "Hamza Chaudhry",
    profession: "Wedding & Event Photographer",
    categoryId: "photographers",
    city: "Karachi",
    area: "Clifton Block 5",
    phone: "+92 301 5554321",
    whatsapp: "+92 301 5554321",
    email: "hamza.visuals@gmail.com",
    experienceYears: 8,
    rating: 4.9,
    reviewCount: 112,
    isAvailable: true,
    availabilityText: "Available for Weekend Events",
    startingPrice: "Rs. 25,000",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300",
    cnicVerified: true,
    policeChecked: true,
    bio: "Award-winning cinematographer and photographer operating in Karachi & Lahore. Equipped with Sony FX3 cinema cameras, 4K drones, and high-end studio lighting for portrait & bridal coverage.",
    servicesOffered: [
      "Wedding & Barat Cinematography",
      "Drone Aerial Coverage",
      "Corporate Event Photography",
      "Product & Commercial Shoots",
    ],
    reviewsList: [
      {
        id: "r5",
        authorName: "Zainab Raza",
        city: "Karachi",
        rating: 5,
        date: "4 days ago",
        comment: "Hamza captured our wedding function in DHA Karachi. The teaser video felt like a Netflix movie! Unbelievable quality.",
      },
    ],
  },
  {
    id: "p-105",
    name: "Umer Farooq",
    profession: "Mobile Auto Mechanic & Diagnostic Tech",
    categoryId: "mechanics",
    city: "Rawalpindi",
    area: "Satellite Town",
    phone: "+92 312 8881122",
    whatsapp: "+92 312 8881122",
    email: "umer.autotech@gmail.com",
    experienceYears: 9,
    rating: 4.7,
    reviewCount: 87,
    isAvailable: true,
    availabilityText: "24/7 Roadside Rescue",
    startingPrice: "Rs. 1,500",
    avatarUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=300",
    cnicVerified: true,
    policeChecked: true,
    bio: "Equipped with OBD2 scanner tools and mobile toolkit. I come directly to your location in Rawalpindi/Islamabad if your car breaks down, won't start, or needs urgent maintenance.",
    servicesOffered: [
      "On-site Computerized Engine Scanning",
      "Brake Pad & Suspension Repair",
      "Battery Jumper & Starter Repair",
      "Oil & Filter Change at Home",
      "Hybrid Battery Diagnostics",
    ],
    reviewsList: [
      {
        id: "r6",
        authorName: "Hamad Sheikh",
        city: "Rawalpindi",
        rating: 5,
        date: "5 days ago",
        comment: "Car stopped working at Murree Road midnight. Umer arrived in 20 minutes and replaced the faulty fuel pump on spot. True lifesaver!",
      },
    ],
  },
  {
    id: "p-106",
    name: "Rashid Minhas",
    profession: "Doorstep Detailer & Car Wash",
    categoryId: "car_wash",
    city: "Islamabad",
    area: "DHA Phase 2",
    phone: "+92 345 7776655",
    whatsapp: "+92 345 7776655",
    email: "rashid.foamwash@gmail.com",
    experienceYears: 5,
    rating: 4.8,
    reviewCount: 76,
    isAvailable: true,
    availabilityText: "Slots Available Today",
    startingPrice: "Rs. 2,000",
    avatarUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=300",
    cnicVerified: true,
    policeChecked: true,
    bio: "Doorstep waterless & pressure wash detailing. Equipped with portable generator, pressure washer, steam interior cleaner, and Meguiar's polishing compounds.",
    servicesOffered: [
      "Interior Deep Steam Wash",
      "Pressure Foam Wash",
      "Engine Bay Detailing",
      "Headlight Restoration",
      "Ceramic Paint Protection",
    ],
    reviewsList: [],
  },
  {
    id: "p-107",
    name: "Bilal Hassan",
    profession: "Senior Inverter AC Technician",
    categoryId: "ac_repair",
    city: "Lahore",
    area: "Johar Town",
    phone: "+92 300 4443322",
    whatsapp: "+92 300 4443322",
    email: "bilal.ac.services@gmail.com",
    experienceYears: 12,
    rating: 4.9,
    reviewCount: 156,
    isAvailable: true,
    availabilityText: "Available Now (30 mins response)",
    startingPrice: "Rs. 1,800",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=300",
    cnicVerified: true,
    policeChecked: true,
    bio: "12+ years experience in Gree, Haier, Orient, Kenwood & Dawlance DC inverter ACs. Specialist in R32/R410 gas charging, PCB repair, leak testing & chemical master service.",
    servicesOffered: [
      "Chemical Master Jet Wash",
      "DC Inverter Gas Refill (R32 / R410)",
      "Outdoor PCB Card Repair",
      "Copper Piping & Installation",
      "Compressor Replacement",
    ],
    reviewsList: [
      {
        id: "r7",
        authorName: "Ahsan Iqbal",
        city: "Lahore",
        rating: 5,
        date: "3 days ago",
        comment: "Cleaned two 1.5 ton Gree inverters in Johar Town. Cooling improved by 100%! Honest pricing.",
      },
    ],
  },
  {
    id: "p-108",
    name: "Sajjad Painter & Decorators",
    profession: "Master Wall Painter & Texture Specialist",
    categoryId: "painters",
    city: "Karachi",
    area: "PECHS / Tariq Road",
    phone: "+92 334 2221100",
    whatsapp: "+92 334 2221100",
    email: "sajjad.paint.decor@gmail.com",
    experienceYears: 15,
    rating: 4.8,
    reviewCount: 64,
    isAvailable: true,
    availabilityText: "Free Site Inspection Available",
    startingPrice: "Rs. 20 / sq.ft",
    avatarUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=300",
    cnicVerified: true,
    policeChecked: true,
    bio: "Professional home painting team. We use ICI Dulux, Berger, and Master Paints. Specialists in damp treatment, rockwall, velvet texture, and exterior weather-shielding.",
    servicesOffered: [
      "Complete House Interior Paint",
      "Exterior Weather-Shield Coating",
      "Damp Proofing & Seepage Treatment",
      "Feature Wall Texture & Stencil Design",
    ],
    reviewsList: [],
  },
  {
    id: "p-109",
    name: "CleanPak Deep Cleaning Services",
    profession: "Residential & Commercial Deep Cleaners",
    categoryId: "home_cleaning",
    city: "Islamabad",
    area: "G-10 / G-11",
    phone: "+92 302 9998877",
    whatsapp: "+92 302 9998877",
    email: "info.cleanpak@gmail.com",
    experienceYears: 6,
    rating: 4.9,
    reviewCount: 130,
    isAvailable: true,
    availabilityText: "Booking Open for Tomorrow",
    startingPrice: "Rs. 4,500",
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=300",
    cnicVerified: true,
    policeChecked: true,
    bio: "Top-rated cleaning company in Islamabad & Rawalpindi. Trained staff, modern extraction machines, eco-friendly chemicals for sofa washing, kitchen degreasing, and post-construction clean.",
    servicesOffered: [
      "Sofa & Mattress Vacuum Wash",
      "Kitchen Exhaust & Tile Degreasing",
      "Full House Move-In Deep Clean",
      "Water Tank Scrubbing",
      "Anti-Bedbug Fumigation",
    ],
    reviewsList: [],
  },
  {
    id: "p-110",
    name: "Chaudhry Landscape & Gardening",
    profession: "Landscape Architect & Plant Specialist",
    categoryId: "garden_services",
    city: "Lahore",
    area: "Model Town",
    phone: "+92 313 6665544",
    whatsapp: "+92 313 6665544",
    email: "chaudhry.greens@gmail.com",
    experienceYears: 11,
    rating: 4.7,
    reviewCount: 45,
    isAvailable: true,
    availabilityText: "Available for Consultations",
    startingPrice: "Rs. 2,500",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=300",
    cnicVerified: true,
    policeChecked: true,
    bio: "Transforming home gardens in Lahore. Fine Fine grass installation, indoor plant care, automatic drip irrigation, flower bed setup, and lawn maintenance packages.",
    servicesOffered: [
      "Lawn Mowing & Weeding",
      "Fine Fine Grass Turf Laying",
      "Artificial Grass Installation",
      "Pest & Fungus Spray for Plants",
      "Rooftop Garden Setup",
    ],
    reviewsList: [],
  },
  {
    id: "p-111",
    name: "Master Usman Electrician",
    profession: "Certified Industrial & Home Electrician",
    categoryId: "electricians",
    city: "Peshawar",
    area: "Hayatabad Phase 3",
    phone: "+92 333 9123456",
    whatsapp: "+92 333 9123456",
    email: "usman.electric.peshawar@gmail.com",
    experienceYears: 8,
    rating: 4.8,
    reviewCount: 52,
    isAvailable: true,
    availabilityText: "Available Now",
    startingPrice: "Rs. 800",
    avatarUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=300",
    cnicVerified: true,
    policeChecked: true,
    bio: "Serving Hayatabad and University Town Peshawar. Reliable electrical repairs, automatic water pump panels, UPS rewiring and ceiling fan fittings.",
    servicesOffered: ["Short Circuit Repair", "UPS Panel Fitting", "Ceiling Fan & Chandelier Installation"],
    reviewsList: [],
  },
  {
    id: "p-112",
    name: "Engr. Farhan Shah",
    profession: "AC Inverter Repair & Cooling Expert",
    categoryId: "ac_repair",
    city: "Karachi",
    area: "Bahria Town Karachi",
    phone: "+92 315 8899000",
    whatsapp: "+92 315 8899000",
    email: "farhan.ac.karachi@gmail.com",
    experienceYears: 9,
    rating: 4.9,
    reviewCount: 88,
    isAvailable: true,
    availabilityText: "Available Now in Bahria Town",
    startingPrice: "Rs. 1,500",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300",
    cnicVerified: true,
    policeChecked: true,
    bio: "Dedicated AC technician covering Bahria Town Karachi, Malir Cantt & Scheme 33. Specialized in inverter jet wash and fast gas recharge.",
    servicesOffered: ["Master AC Service", "Gas Charging", "Inverter Error Code Diagnosis"],
    reviewsList: [],
  },
];
